USE [rbi]
GO

/****** Object:  Table [dbo].[TBL_47_DM_THIN_TANK]    Script Date: 8/21/2019 10:19:09 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TBL_47_DM_THIN_TANK](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Art] [float] NULL,
	[E] [float] NULL,
	[Insp] [int] NULL,
	[D] [float] NULL,
	[C] [float] NULL,
	[B] [float] NULL,
	[A] [float] NULL,
 CONSTRAINT [PK_TBL_47_DM_THIN_TANK] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


