USE [rbi]
GO

/****** Object:  Table [dbo].[TBL_46_DM_THIN]    Script Date: 8/21/2019 10:16:19 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TBL_46_DM_THIN](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NumberOrder] [int] NULL,
	[EffectivenessCode] [nvarchar](50) NULL,
	[ConditionalProbability] [float] NULL,
 CONSTRAINT [PK_TBL46DM_THIN] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


